apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

images:
  - name: chocoletter-client-image
    newName: 211125633965.dkr.ecr.ap-northeast-2.amazonaws.com/chocoletter-client
    newTag: "0.1"

patches:
  - target:
      kind: Deployment
      name: chocoletter-client-base-deploy
    path: deploy-patch.yaml
  - target:
      kind: Service
      name: chocoletter-client-base-service
    path: service-patch.yaml
  - target:
      kind: HTTPRoute
      name: chocoletter-client-base-route
    path: http-route-patch.yaml
