apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chocoletter-external-secret-server-after
  namespace: chocoletter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: chocoletter-server-after-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/after-chocoletter-server
