apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - ../base
  - external-secret.yaml

images:
  - name: chocoletter-chat-image
    newName: harbor.onprem.local/son/chocoletter-chat
    newTag: "0.3"

patches:
  - target:
      kind: Deployment
      name: chocoletter-chat-base-deploy
    path: deploy-patch.yaml
  - target:
      kind: Service
      name: chocoletter-chat-base-service
    path: service-patch.yaml
  - target:
      kind: HTTPRoute
      name: chocoletter-chat-base-route
    path: http-route-patch.yaml
