apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - harbor-registry-external-secret.yaml
  - http-route.yaml
  - external-secret.yaml

images:
  - name: chocoletter-server-image
    newName: harbor.onprem.local/son/chocoletter-server-after
    newTag: "0.3"

patches:
  # Deployment 이름 및 labels/selector 변경
  - target:
      kind: Deployment
      name: refac-chocoletter-server
    patch: |-
      - op: replace
        path: /metadata/name
        value: refac-chocoletter-server-after
      - op: replace
        path: /spec/selector/matchLabels/app
        value: chocoletter-server-after
      - op: replace
        path: /spec/template/metadata/labels/app
        value: chocoletter-server-after
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: chocoletter-server-after
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{name: harbor-registry-key}]
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{secretRef: {name: chocoletter-server-after-secret}}]
  # Service 이름 및 selector 변경
  - target:
      kind: Service
      name: chocoletter-server-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: chocoletter-server-after-service
      - op: replace
        path: /spec/selector/app
        value: chocoletter-server-after
